name = "sky-chat-workers"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Isi dengan Account ID dari Cloudflare Dashboard → kanan bawah
account_id = "dae83f992fc1121e1ea6c8f1ab7f1d76"

[vars]
ENVIRONMENT = "production"
# JWT_SECRET JANGAN letak di sini — gunakan:
#   cd workers && npx wrangler secret put JWT_SECRET

[[d1_databases]]
binding = "DB"
database_name = "sky-chat-db"
# Isi setelah buat D1 database di Cloudflare Dashboard
database_id = "a42bba23-33df-46c0-abe0-c58d415282e6"

[[kv_namespaces]]
binding = "KV"
id = "bd018c394d374b3b821e55d0dab84d6d"

[[r2_buckets]]
binding = "R2"
bucket_name = "sky-chat-media"

[[durable_objects.bindings]]
name = "SUB_SERVER"
class_name = "SubServer"

[[migrations]]
tag = "v1"
new_classes = ["SubServer"]

[triggers]
crons = ["0 * * * *"]
